dev/Solemne1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from administrator.urls import administrator_patterns
from core.urls import core_urlpatterns
from ejemplos.urls import ejemplos_urlpatterns
from gestioncliente.urls import gestioncliente_urlpatterns

urlpatterns = [
    path('',include(core_urlpatterns)),
]
from ordencompra.urls import ordencompra_urlpatterns
from prov.urls import prov_urlpatterns
from categoria.urls import categoria_urlpatterns
from product.urls import product_urlpatterns
from ventas.urls import ventas_urlpatterns
from cotizacion.urls import cotizacion_urlpatterns

urlpatterns = [
    path('',include(core_urlpatterns)),
    path('ventas/',include(ventas_urlpatterns)),
    path('categoria/',include(categoria_urlpatterns)),
    path('product/',include(product_urlpatterns)),
    path('cotizacion/',include(cotizacion_urlpatterns)),
    path('prov/',include(prov_urlpatterns)),
    path('ordencompra/',include(ordencompra_urlpatterns)),
    path('gestioncliente/',include(gestioncliente_urlpatterns)),
    path('ejemplos/',include(ejemplos_urlpatterns)),
    path("administrator/",include(administrator_patterns)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),

]
admin.site.site_header='Administrador Bussiness_Solutions'
admin.site.site_title='bussinessSolutions'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


dev/product/urls.py
from django.urls import path
from product import views #importará los métodos que generemos en nuestra app
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *

product_urlpatterns = [

    path('ejemplos_main/',views.ejemplos_main,name="ejemplos_main"),
    path('agregar_producto/',views.agregar_producto,name="agregar_producto"),
    #path('productos/', listar_producto, name='listar_productos'),
    path('listar_producto/',views.listar_producto,name="listar_producto"),
    path('actualizar_producto/<id>/',views.actualizar_producto,name="actualizar_producto"),
    path('eliminar_producto/<id>/',views.eliminar_producto,name="eliminar_producto"),

    path('ejemplos_carga_masiva/',views.ejemplos_carga_masiva,name="ejemplos_carga_masiva"),
    path('ejemplos_carga_masiva_save/',views.ejemplos_carga_masiva_save,name="ejemplos_carga_masiva_save"),
    path('import_file/',views.import_file,name="import_file"),
    path('generar_reporte_prod/', views.generar_reporte_prod, name='generar_reporte_prod'),
    path('dashboard1/', views.dashboard1, name='dashboard1'),
]


dev/prov/urls.py
from django.urls import path
from prov import views #importará los métodos que generemos en nuestra app
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *

prov_urlpatterns = [
    path('proveedor/',views.proveedor_main,name="proveedor_main"),
    path('agregar_proveedor/',views.agregar_proveedor,name="agregar_proveedor"),
    path('listar_proveedor/',views.listar_proveedor,name="listar_proveedor"),
    path('actualizar_proveedor/<id>/',views.actualizar_proveedor,name="actualizar_proveedor"),
    path('eliminar_proveedor/<id>/',views.eliminar_proveedor,name="eliminar_proveedor"),

    path('generar_reporte_prov/', views.generar_reporte_prov, name='generar_reporte_prov'),

    path('carga_masiva_prov/',views.carga_masiva_prov,name="carga_masiva_prov"),
    path('carga_masiva_saveprov/',views.carga_masiva_saveprov,name="carga_masiva_saveprov"),
    path('import_file/',views.import_file,name="import_file"),
    path('dashboard2/', views.dashboard2, name='dashboard2'),
]

dev/product/models.py
from django.db import models
from prov.models import Proveedor
from categoria.models import Categoria

class Producto(models.Model):
    proveedor=models.ManyToManyField(Proveedor)
    nombre = models.CharField(max_length=100)
    precio = models.IntegerField()
    descripcion = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    talla = models.CharField(max_length=4)
    stock=models.IntegerField()

    def __str__(self):
        return self.nombre

dev/product/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Producto



class ProductoForm(forms.ModelForm):
    class Meta: 
        model = Producto
        fields = '__all__'

dev/product/views.py
import json
import pandas as pd
import xlwt
#nuevas importaciones 30-05-2022
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render,redirect,get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from registration.models import Profile
#fin nuevas importaciones 30-05-2022
from django.db.models import Count, Avg, Q
from django.shortcuts import render
from rest_framework import generics, viewsets
from rest_framework.decorators import (
	api_view, authentication_classes, permission_classes)
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from rest_framework.views import APIView
from product.models import Producto
from .forms import ProductoForm
from prov.models import Proveedor
from django.views.generic import View
from .models import Producto
from django.db.models import Q
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from django.template.loader import get_template
from django.template import Context
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
from datetime import date
from django.urls import reverse
import plotly.graph_objects as go

from django.shortcuts import render, redirect
from .forms import ProductoForm
from .models import Producto
from django.contrib import messages


def dashboard1(request):

    # Obtener todos los productos
    productos = Producto.objects.all()

    # Gráfico de barras: Stock por producto
    nombres_productos = [producto.nombre for producto in productos]
    stock_productos = [producto.stock for producto in productos]

    fig1 = go.Figure(data=go.Bar(x=nombres_productos, y=stock_productos))
    fig1.update_layout(title='Stock por producto')

    # Gráfico de pastel: Distribución de precios de los productos
    precios = [producto.precio for producto in productos]
    labels2 = ['<10000', '10000-20000', '20000-25000', '25000-35000', '>35000']
    values2 = [
        len([precio for precio in precios if precio < 10000]),
        len([precio for precio in precios if 10000 <= precio < 20000]),
        len([precio for precio in precios if 20000 <= precio < 25000]),
        len([precio for precio in precios if 25000 <= precio < 35000]),
        len([precio for precio in precios if precio >= 35000])
    ]

    fig2 = go.Figure(data=[go.Pie(labels=labels2, values=values2)])
    fig2.update_layout(title='Distribución de precios de los productos')

    # Datos útiles
    cantidad_productos = len(productos)
    producto_mas_caro = max(productos, key=lambda producto: producto.precio)
    producto_mas_barato = min(productos, key=lambda producto: producto.precio)

    context = {
        'plot_div1': fig1.to_html(full_html=False),
        'plot_div2': fig2.to_html(full_html=False),
        'cantidad_productos': cantidad_productos,
        'producto_mas_caro': producto_mas_caro,
        'producto_mas_barato': producto_mas_barato,
    }

    return render(request, 'product/dashboard1.html',context)

@login_required
def listar_producto(request):
    busqueda = request.GET.get("buscar")
    productos = Producto.objects.all()

    if busqueda:
        productos = productos.filter(nombre__icontains=busqueda)

    if 'generar_reporte' in request.GET:
        return redirect(reverse('generar_reporte') + '?buscar=' + busqueda)
    
    if not busqueda:
        productos = Producto.objects.all()

    return render(request, 'product/listar.html', {'productos': productos, 'buscar': busqueda})




@login_required

def generar_reporte_prod(request):
    busqueda = request.GET.get("buscar")
    productos = Producto.objects.all()
    if busqueda:
        productos = productos.filter(nombre__icontains=busqueda)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="reporte_productos.pdf"'
    doc = SimpleDocTemplate(response, pagesize=letter)
    data = []
    data.append(['Nombre', 'Precio', 'Descripción', 'Talla', 'Categoría'])
    for producto in productos:
        data.append([producto.nombre, producto.precio, producto.descripcion, producto.talla, producto.categoria.nombre])
    # Crear los estilos de tabla y párrafo
    styles = getSampleStyleSheet()
    style_table = TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), '#CCCCCC'),
    ('TEXTCOLOR', (0, 0), (-1, 0), '#000000'),
    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
    ('FONTSIZE', (0, 0), (-1, 0), 12),
    ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
    ('BACKGROUND', (0, 1), (-1, -1), '#EEEEEE'),
    ('COLWIDTHS', (0, 0), (-1, -1), 60),  # Ajusta el ancho de todas las columnas
    ])
    style_paragraph = ParagraphStyle(
        name='BodyText',
        parent=styles['Normal'],
        spaceBefore=6,
        spaceAfter=6,
    )

    # Crear la tabla con los datos y aplicar estilos
    table = Table(data)
    table.setStyle(style_table)

    # Agregar la tabla al documento
    elements = [Paragraph('Informe de Productos', styles['Heading1'])]
    elements.append(Paragraph('Fecha: ' + date.today().strftime('%d/%m/%Y'), style_paragraph))
    elements.append(Paragraph('Listado de productos:', styles['Heading3']))
    elements.append(table)

    doc.build(elements)

    return response








@login_required
def ejemplos_main(request):
    profile = Profile.objects.get(user_id=request.user.id)
    if profile.group_id != 1:
        messages.add_message(request, messages.INFO, 'Intenta ingresar a una area para la que no tiene permisos')
        return redirect('check_group_main')
    template_name = 'product/ejemplos_main.html'
    return render(request,template_name,{'profile':profile})

#PRODUCTOS
from django.shortcuts import render, redirect
from .forms import ProductoForm
from .models import Producto
from django.contrib import messages

def agregar_producto(request):
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.add_message(request, messages.SUCCESS, 'Producto creado!')
            return redirect(to="listar_producto")
    else:
        formulario = ProductoForm()

    proveedores = Proveedor.objects.all()
    data = {
        'form': formulario,
        'proveedores': proveedores,
    }

    return render(request, 'product/agregar.html', data)



    # profile = Profile.objects.get(user_id=request.user.id)
    # if profile.group_id != 1:
    #     messages.add_message(request, messages.INFO, 'Intenta ingresar a una area para la que no tiene permisos')
    #     return redirect('check_group_main')
    # template_name = 'ejemplos/agregar.html'
    # return render(request,template_name,{'profile':profile})
#@login_required
#def listar_producto(request):
    #productos = Producto.objects.all()
    #data={
        #'productos': productos
    #}
    #return render(request, 'product/listar.html',data)
@login_required
def actualizar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    proveedores = Proveedor.objects.all()  # Obtén la lista de proveedores
    data = {
        'form': ProductoForm(instance=producto),
        'proveedores': proveedores,  # Pasa la lista de proveedores al contexto
    }
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto)
        if formulario.is_valid():
            formulario.save()
            return redirect(to="listar_producto")
    messages.add_message(request, messages.INFO, 'Producto actualizado!')
    return render(request, 'product/modificar.html', data)

@login_required
def eliminar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    messages.add_message(request, messages.INFO, 'Producto eliminado!')
    return redirect(to="listar_producto")
#CARGA MASIVA PRODUCTO
@login_required
def ejemplos_carga_masiva(request):
    profiles = Profile.objects.get(user_id = request.user.id)
    if profiles.group_id != 1:
        messages.add_message(request, messages.INFO, 'Intenta ingresar a una area para la que no tiene permisos')
        return redirect('check_group_main')
    template_name = 'product/ejemplos_carga_masiva.html'
    return render(request,template_name,{'profiles':profiles})

@login_required
def import_file(request):
    profiles = Profile.objects.get(user_id = request.user.id)
    if profiles.group_id != 1:
        messages.add_message(request, messages.INFO, 'Intenta ingresar a una area para la que no tiene permisos')
        return redirect('check_group_main')
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="archivo_importacion.xls"'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('carga_masiva')
    row_num = 0
    columns = ['Nombre Producto','Precio','Descripcion','Talla','Categoria','Stock']
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)
    font_style = xlwt.XFStyle()
    date_format = xlwt.XFStyle()
    date_format.num_format_str = 'dd/MM/yyyy'
    for row in range(1):
        row_num += 1
        for col_num in range(6):
            if col_num == 0:
                ws.write(row_num, col_num, 'ej: producto' , font_style)
            if col_num == 1:                           

dev/product/templates/product/agregar.html
{% extends "administrator/index_main.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <style>
            body {
                font-family: sans-serif;
                background-color: #f7f7f7;
            }

            .title {
                margin-bottom: 2rem;
                text-align: center;
            }

            .search-container {
                display: flex;
                align-items: center;
                margin-bottom: 1rem;
            }

            .search-input {
                margin-right: 0.5rem;
            }

            .btn {
                display: inline-block;
                padding: 0.5rem 1rem;
                margin: 0.5rem;
                background-color: #007bff;
                color: #fff;
                text-decoration: none;
                border-radius: 0.25rem;
            }

            .table {
                margin-top: 1rem;
                background-color: #f8f9fa;
            }

            .table th,
            .table td {
                padding: 0.5rem;
            }

            .table th {
                text-align: left;
            }

            .center {
                text-align: center;
            }

            .button-container {
                margin-top: 1rem;
                text-align: center;
            }

            .button-container a {
                margin-right: 0.5rem;
            }

            .form-container {
                display: flex;
                flex-direction: column;
                align-items: center;
            }

            .form-container form {
                width: 100%;
                max-width: 400px;
            }

            .form-container .form-group {
                margin-bottom: 1rem;
            }

            .form-container label {
                font-weight: bold;
            }

            .form-container .btn-container {
                display: flex;
                justify-content: center;
                margin-top: 1rem;
            }
        </style>
        <div class="col-12 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="title">NUEVO PRODUCTO</h2>
                    <hr>
                    <div class="form-container">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_proveedor">Proveedor:</label>
                                <select name="proveedor" id="id_proveedor" class="form-control">
                                    {% for proveedor in proveedores %}
                                        <option value="{{ proveedor.id }}">{{ proveedor.empresa }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="id_nombre">Nombre:</label>
                                {{ form.nombre }}
                            </div>
                            <div class="form-group">
                                <label for="id_precio">Precio:</label>
                                {{ form.precio }}
                            </div>
                            <div class="form-group">
                                <label for="id_descripcion">Descripción:</label>
                                {{ form.descripcion }}
                            </div>
                            <div class="form-group">
                                <label for="id_categoria">Categoría:</label>
                                {{ form.categoria }}
                            </div>
                            <div class="form-group">
                                <label for="id_talla">Talla:</label>
                                {{ form.talla }}
                            </div>
                            <div class="form-group">
                                <label for="id_stock">Stock:</label>
                                {{ form.stock }}
                            </div>
                            <div class="btn-container">
                                <input type="submit" value="Guardar" class="btn btn-primary">
                                <a href="{% url 'admin_main' %}" class="btn btn-danger">Volver</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dev/product/templates/product/dashboard1.html
{% extends "administrator/index_main.html" %}
{% load static %}
{% block content %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
    <!-- Agrega los siguientes scripts para cargar Plotly -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f7f7f7;
            margin: 0;
            padding: 20px;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
            margin-left: 100px;
        }
        .container {
            display: flex;
            justify-content: center; /* Centrado horizontal */
            margin-left: 240px; /* Desplazamiento hacia la derecha */
        }
        .dashboard {
            width: 100%; /* Ancho completo */
            max-width: 800px; /* Ancho máximo para limitar el tamaño */
        }
        .data-container {
            background-color: #ffffff;
            border: 1px solid #dddddd;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 20px;
            margin-left: 100px;
            text-align: center; /* Centrado del contenido */
        }
        .data-container h2 {
            margin-top: 0;
            
        }
        .chart-container1 {
            width: 650px;
            background-color: #ffffff;
            border: 1px solid #dddddd;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 20px;
            margin-left: -200px;
        }
        .chart-container2 {
            width: 650px;
            background-color: #ffffff;
            border: 1px solid #dddddd;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 20px;
            margin-left: 500px;
            margin-top: -512px;
        }
        .chart-container h2 {
            margin-top: 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="dashboard">
            <h1>Dashboard de Producto</h1>

            <div class="data-container">
                <h2>Datos útiles</h2>
                <p>Cantidad total de productos: {{ cantidad_productos }}</p>
                <p>Producto más caro: {{ producto_mas_caro }}</p>
                <p>Producto más barato: {{ producto_mas_barato }}</p>
            </div>

            <div class="chart-container1">
                <!-- Div para incrustar el primer gráfico generado por Plotly -->
                {{ plot_div1|safe }}
            </div>

            <div class="chart-container2">
                <!-- Div para incrustar el segundo gráfico generado por Plotly -->
                {{ plot_div2|safe }}
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

dev/product/templates/product/ejemplos_carga_masiva.html
{% extends "administrator/index_main.html" %}
{% load static %}
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Carga Masiva de Usuarios</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f7f7f7;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
            padding: 0;
        }

        .form-container {
            max-width: 600px;
            padding: 60px;
            border-radius: 10px;
            box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
            background-color: #ffffff;
            text-align: center;
        }

        .form-container h3 {
            margin-top: 0;
            margin-bottom: 30px;
            font-size: 30px;
            font-weight: bold;
            color: #333333;
        }

        .form-group {
            margin-bottom: 30px;
            text-align: left;
        }

        .form-group label {
            display: block;
            font-size: 16px;
            font-weight: bold;
            color: #666666;
            margin-bottom: 12px;
        }

        .form-control {
            width: 100%;
            height: 50px;
            padding: 12px;
            font-size: 16px;
            border: 1px solid #dddddd;
            border-radius: 4px;
            background-color: #ffffff;
            color: #333333;
            transition: border-color 0.3s ease-in-out;
        }

        .form-control:focus {
            outline: none;
            border-color: #007bff;
            box-shadow: 0px 0px 0px 3px rgba(0, 123, 255, 0.1);
        }

        .btn-primary {
            width: 100%;
            height: 50px;
            font-size: 18px;
            font-weight: bold;
            border-radius: 4px;
            background-color: #007bff;
            border: none;
            color: #ffffff;
            transition: background-color 0.3s ease-in-out;
        }
        .btn-primary1 {
            display: inline-flex;
        align-items: center;
        justify-content: center;
        text-decoration: none;
        width: 100%;
        height: 50px;
        font-size: 20px;
        font-weight: bold;
        border-radius: 6px;
        background-color: #007bff;
        border: none;
        color: #ffffff;
        transition: background-color 0.3s ease-in-out;
        }


        .btn-primary:hover {
            background-color: #0056b3;
        }
        .btn-primary1:hover{
            background-color: #0056b3;
        }

        .btn-download {
            display: inline-flex;
            align-items: center;
            height: 50px;
            justify-content: center;
            text-decoration: none;
            padding: 12px 24px;
            font-size: 16px;
            font-weight: bold;
            border-radius: 4px;
            background-color: #ffffff;
            color: #007bff;
            border: 1px solid #007bff;
            transition: background-color 0.3s ease-in-out;
        }

        .btn-download i {
            margin-right: 12px;
            
        }

        .btn-download:hover {
            background-color: #007bff;
            color: #ffffff;
        }

    </style>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="form-container">
        <h3>Carga Masiva de productos</h3>
        {% if profiles.group_id == 1 %}
        <form action="{% url 'carga_masiva_save_user' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <a href="{% url 'import_file' %}" class="btn-download">
                    <i class="fas fa-download"></i> Descargar archivo de importación .xlsx
                </a>
            </div>
            <div class="form-group">
                <input type="file" name="myfile" class="form-control" required>
            </div>
            <div class="form-group">
                <button class="btn-primary" type="submit">Cargar</button>
            </div>
            <div class="form-group">
                <a href="{% url 'users_main' %}" class="btn-primary1">Volver</a>
            </div>
        </form>
        {% endif %}
    </div>
</body>
</html>
    {% if messages %}
    {% for me in messages %}
    <script>
        Swal.fire({
            "title": "CARGA",
            "text": "{{me}}",
            "icon": "success",
        })
    </script>
    {% endfor %}
{% endif %}
{% endblock %}

dev/product/templates/product/ejemplos_main.html
{% extends "administrator/index_main.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Gestión Productos y Categorías</title>
    <style>
        body {
            font-family: sans-serif; 
        }

        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .title {
            margin-top: 2rem;
            margin-bottom: 10rem; /* Agregar margen inferior al título */
            text-align: center;
        }

        .card {
            width: 80%;
            margin-top: 2rem;
        }

        .return-button {
            margin-top: 2rem;
            text-align: center;
        }

        /* Estilos para los botones */
        .btn {
            display: inline-block;
            padding: 0.5rem 1rem;
            margin: 0.5rem;
            background-color: #000;
            color: #fff;
            text-decoration: none;
            border-radius: 0.25rem;
        }

        .btn-dark {
            background-color: #343a40;
        }
    </style>
</head>
<body>
    <h1 class="title text-blue">GESTIÓN PRODUCTOS Y CATEGORÍAS</h1>
    <div class="container">
        <a href="{% url 'listar_producto' %}" class="btn btn-dark">Listado Productos</a>
        <a href="{% url 'agregar_producto' %}" class="btn btn-dark">Nuevo Producto</a>
        <a href="{% url 'ejemplos_carga_masiva' %}" class="btn btn-dark">Carga masiva de Producto</a>
        <a href="{% url 'listar_categoria' %}" class="btn btn-dark">Listado Categoría</a>
        <a href="{% url 'agregar_categoria' %}" class="btn btn-dark">Nuevo Categoría</a>
        <a href="{% url 'carga_masiva_categoria' %}" class="btn btn-dark">Carga masiva de Categoría</a>
        <div class="return-button">
            <a href="{% url 'admin_main' %}" class="btn">Volver</a>
        </div>
    </div>
</body>
</html>
{% endblock %}